packages/refine/package.json
packages/refine/src/components/Layout/index.tsx
packages/refine/src/components/NamespacesFilter/index.tsx
packages/refine/src/hooks/useEagleTable/index.tsx
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/pages/configmap/list/index.tsx
packages/refine/src/pages/cronjobs/list/index.tsx
packages/refine/src/pages/daemonsets/list/index.tsx
packages/refine/src/pages/deployments/list/index.tsx
packages/refine/src/pages/jobs/list/index.tsx
packages/refine/src/pages/statefulSets/list/index.tsx
yarn.lock

对比之后暂时使用 localStorage 存储 filter 信息，更容易实现路由变化、页面重新打开时的 filter 保留。
对 filter 的读写逻辑封装在了 NamespaceFilter 内部，未来可以配置为后端 API 实现。

add namespace filter

---

packages/refine/src/constants/k8s.ts
packages/refine/src/pages/cronjobs/create/index.tsx
packages/refine/src/pages/daemonsets/create/index.tsx
packages/refine/src/pages/deployments/create/index.tsx
packages/refine/src/pages/jobs/create/index.tsx
packages/refine/src/pages/pods/create/index.tsx
packages/refine/src/pages/statefulsets/create/index.tsx

#40 
增加必要的字段，让用户更容易基于初始值完成资源创建

improve workload form init values

---

packages/refine/src/components/PageShow/PageShow.tsx
packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/components/WorkloadDropdown/index.tsx
packages/refine/src/constants/k8s.ts
packages/refine/src/hooks/useEagleForm.ts
packages/refine/src/hooks/useEagleTable/index.tsx
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/model/workload-model.ts
packages/refine/src/pages/deployments/list/index.tsx
packages/refine/src/pages/deployments/show/index.tsx
packages/refine/src/utils/k8s.ts

1. 在 workload model 中增加了 redeploy 方法，用于构造一个用于重新部署的 yaml，实际上是通过更新 annotation 触发重建
2. 扩展 list 和 show 页面，支持传入 Dropdown props，不传入则使用默认的 K8sDropdown
3. 实现 WorkloadDropdown，扩展 K8sDropdown，增加 redeploy 入口

impl workload redeploy action

---

packages/refine/src/components/ErrorContent/index.tsx
packages/refine/src/components/YamlEditor/YamlEditorComponent.tsx
packages/refine/src/components/YamlForm/index.tsx
packages/refine/src/hooks/useEagleForm.ts
packages/refine/src/hooks/useK8sYamlEditor.ts
packages/refine/src/hooks/useSchema.ts
packages/refine/src/locales/en-US/dovetail.json
packages/refine/src/locales/zh-CN/dovetail.json

添加获取 Schema 的不同策略。
获取 Schema 失败时展示错误页面
获取失败时正常展示编辑器，但无 Schema 校验
获取成功有 Schema 校验
不发起 Schema 请求，无校验

feat: add schema strategy for editor

---

packages/refine/src/components/YamlForm/index.tsx
packages/refine/src/hooks/useEagleForm.ts

修复编辑页面刷新后表单值不正确的问题，并关闭 liveMode 防止后续值变化时意外修改表单

fix: turn off the live mode in yaml form

---

packages/refine/package.json
packages/refine/src/App.tsx
packages/refine/src/Dovetail.tsx
packages/refine/src/components/ListPage/index.tsx
packages/refine/src/contexts/index.ts
packages/refine/src/index.ts
yarn.lock

1. 为了支持应用中存在多个 d2 实例的情况，需要让多个 d2 实例共享 globalStore。所以 d2 需要支持传入 globalStore 作为参数
2. ListPage 允许传className给table的小改动

pass globalStore to d2

---

packages/refine/src/components/CronjobJobsTable/index.tsx
packages/refine/src/components/PodContainersTable/PodContainersTable.tsx
packages/refine/src/components/ResourceCRUD/list/index.tsx
packages/refine/src/components/StateTag/StateTag.tsx
packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx
packages/refine/src/constants/index.ts
packages/refine/src/constants/state.ts
packages/refine/src/hooks/useEagleTable/columns.tsx
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/models/cronjob-model.ts
packages/refine/src/models/daemonset-model.ts
packages/refine/src/models/deployment-model.ts
packages/refine/src/models/index.ts
packages/refine/src/models/job-model.ts
packages/refine/src/models/pod-model.ts
packages/refine/src/models/statefulset-model.ts
packages/refine/src/pages/cronjobs/list/index.tsx
packages/refine/src/pages/daemonsets/list/index.tsx
packages/refine/src/pages/deployments/list/index.tsx
packages/refine/src/pages/jobs/index.ts
packages/refine/src/pages/pods/list/index.tsx
packages/refine/src/pages/statefulsets/list/index.tsx
packages/refine/src/plugins/model-plugin.ts

添加workload资源的状态字段和对应的Renderer、Field
因为每个资源的状态判断规则都不同，所以给每个资源都创建了Model

add stateDisplay for workloads

---

packages/refine/src/components/EditField/index.tsx
packages/refine/src/components/FormErrorAlert/index.tsx
packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/components/ShowContent/fields.tsx
packages/refine/src/components/WorkloadReplicas/index.tsx
packages/refine/src/components/YamlForm/index.tsx
packages/refine/src/hooks/useSubmitForm.ts
packages/refine/src/types/modal.d.ts
packages/refine/src/utils/error.ts

编辑副本数改为弹窗方式。
主要实现的组件有 EditFieldModal、WorkloadReplicasForm。
EditFieldModal 为通用的编辑字段模态框组件，支持传入自定义实现的表单组件。
WorkloadReplicasForm 为编辑副本数的表单组件，其将表单值状态都内聚在组件内部，以便在模态框关闭时销毁该组件来重置表单状态。

feat: use modal to edit replicas

---

packages/refine/src/components/DrawerShow/DrawerShow.tsx
packages/refine/src/components/ImageNames/index.tsx
packages/refine/src/components/PageShow/PageShow.tsx
packages/refine/src/components/ResourceCRUD/ResourceCRUD.tsx
packages/refine/src/components/ResourceCRUD/show/index.tsx
packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/components/ShowContent/fields.tsx
packages/refine/src/components/WorkloadReplicas/index.tsx
packages/refine/src/pages/configmaps/index.ts
packages/refine/src/pages/cronjobs/show/index.tsx
packages/refine/src/pages/daemonsets/show/index.tsx
packages/refine/src/pages/deployments/show/index.tsx
packages/refine/src/pages/jobs/index.ts
packages/refine/src/pages/pods/show/index.tsx
packages/refine/src/pages/secrets/index.ts
packages/refine/src/pages/services/index.ts
packages/refine/src/pages/statefulsets/show/index.tsx
packages/refine/src/types/resource.ts

修改详情页字段数据结构。
```ts
export type ShowField<Model extends ResourceModel> = {
key: string;
title: string;
path: string[];
labelWidth?: string;
col?: number;
render?: (val: unknown, record: Model) => React.ReactElement | undefined;
renderContent?: (val: unknown, record: Model) => React.ReactElement | undefined;
};
export type ShowTabField<Model extends ResourceModel> = {
key: string;
title: string;
path: string[];
renderContent?: (val: unknown, record: Model) => React.ReactElement | undefined;
};
export interface Detail<Model extends ResourceModel = ResourceModel> {
title?: string;
descriptions?: ShowField<Model>[];
groups?: {
fields: ShowField<Model>[];
}[];
tabs?: ShowTabField<Model>[];
}
```
详情页目前分为 descriptions, groups, tabs 三个区域。
descriptions 可放置多个字段。
可添加多个 groups，每个 group …

feat: change the data struct of detail props

---

packages/refine/package.json
packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/components/index.ts

之前用status.phase 判断详情页中是否可以显示状态，但这样不准确，不是所有有状态的资源都是通过status.phase获取状态的。所以用 stateDisplay 来判断。stateDisplay 是 Model 中自定义的状态。

use stateDisplay to get state in ShowContent

---

packages/refine/package.json
packages/refine/src/App.tsx
packages/refine/src/Dovetail.tsx
packages/refine/src/components/CronjobJobsTable/index.tsx
packages/refine/src/components/EventsTable/EventsTable.tsx
packages/refine/src/components/FormModal/index.tsx
packages/refine/src/components/ResourceCRUD/list/index.tsx
packages/refine/src/components/ShowContent/fields.tsx
packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx
packages/refine/src/hooks/useEagleTable/columns.tsx
packages/refine/src/index.ts
packages/refine/src/locales/en-US/dovetail.json
packages/refine/src/pages/configmaps/index.ts
packages/refine/src/pages/cronjobs/list/index.tsx
packages/refine/src/pages/cronjobs/show/index.tsx
packages/refine/src/pages/daemonsets/list/index.tsx
packages/refine/src/pages/daemonsets/show/index.tsx
packages/refine/src/pages/deployments/list/index.tsx
packages/refine/src/pages/deployments/show/index.tsx
packages/refine/src/pages/ingresses/index.tsx
packages/refine/src/pages/jobs/index.ts
packages/refine/src/pages/networkPolicies/index.tsx
packages/refine/src/pages/pods/list/index.tsx
packages/refine/src/pages/pods/show/index.tsx
packages/refine/src/pages/secrets/index.ts
packages/refine/src/pages/services/index.ts
packages/refine/src/pages/statefulsets/list/index.tsx
packages/refine/src/pages/statefulsets/show/index.tsx

主要目的是能够让ColumnRenderer和ShowFiled中的title的i18n能够响应语言切换的变化。
1. d2 暴露自己的 i18n 实例出来
2. ColumnRenderer和ShowFiled的函数都接受一个 i18n 实例为参数，因为这两个东西不是组件，不能用 hook。这个 i18n 实例应该是 d2 i18n实例，有d2的词条，而不是应用的 i18n。
3. 给Dovetail组件加了一个I18nextProvider，让 d2 内部的 useTranslation 拿到的都是 d2 的 i18n。

pass i18n to columnRendereer and showField

---

packages/refine/src/Dovetail.tsx
packages/refine/src/hooks/useEagleForm.ts

1. 禁止 refine 发送收集信息的请求，https://refine.dev/docs/core/refine-component/#disabletelemetry
2. 修复再次打开模态框时 YAML 没有折叠的问题

fix: fix the yaml didn't fold after opening modal again and disable the telemetry

---

packages/refine/package.json
packages/refine/src/Dovetail.tsx
packages/refine/src/components/PageShow/PageShow.tsx
packages/refine/src/locales/zh-CN/dovetail.json
yarn.lock

1. 添加了 notificationProvider，用来让refine弹出toast
2. 当通过url访问一个不存在的资源（或者获取资源详情出错），则报错，并返回到资源的列表页

fallback to list when resource doesn't exist

---

packages/refine/src/components/FormModal/index.tsx
packages/refine/src/components/YamlForm/index.tsx
packages/refine/src/hooks/useEagleForm.ts

修复编辑器偶尔出现编辑过程中数据更新的问题。
之前通过设置 `liveMode: 'off'` 来关闭数据更新似乎不能完全组件数据更新，现在移除 `useEffect` 中更新编辑器值的逻辑，只在编辑器创建的时候初始化一次，并添加 loading 之后再渲染编辑器的逻辑，以保证编辑器创建的时候已经完成数据获取。

fix: changes when the editor sets the initial value

---

packages/refine/src/components/Time/index.tsx

only use unit up to day when displaying age

---

packages/refine/src/components/ServiceComponents/index.tsx
packages/refine/src/hooks/index.ts
packages/refine/src/hooks/useEagleTable/columns.tsx
packages/refine/src/locales/en-US/dovetail.json
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/pages/services/index.tsx

在nodeport类型的service的「集群外访问方式中」，用实际的集群vip，替代「任意 IP」，拼成可跳转的链接

use cluster vip in nodePort Service

---

packages/refine/src/components/Form/FormModal.tsx
packages/refine/src/components/Form/useRefineForm.ts

1. 修复创建资源成功后的toast文案错误，正确传递 kind 参数
2. refineForm弹窗成功创建资源后，不需要跳转页面

fix refine form bugs

---

packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/useReactHookForm.tsx
packages/refine/src/components/Form/useRefineForm.ts

修复 RefineForm 收到socket事件时，会用资源的原始值，覆盖用户已输入的值的bug。

fix RefineForm will override form value on event

---

packages/refine/src/components/CronjobJobsTable/index.tsx
packages/refine/src/hooks/useEagleTable/columns.tsx

job的pods数量是用字符串排序的，所以会有些问题。现在改成使用succeeded来排序。
顺便修改了一些错误的类型。CompletionsCountColumnRenderer不需要兼容 Cronjob

use succeeded number to sort in  job pods column

---

packages/refine/src/Dovetail.tsx
packages/refine/src/components/PageShow/PageShow.tsx

除详情页获取失败时会提示「资源不存在」，其他情况下获取数据失败不再进行提示

fix: don't open toast when getting data fails

---

packages/refine/package.json
packages/refine/src/models/ingress-model.ts

启用 Contour 时，contour-envoy 服务的 type 设置为 NodePort 时，Ingress 的规则中请求端后面要加上端口

SKS-2783 add port in ingress rule

---

packages/refine/package.json
packages/refine/src/components/index.ts
packages/refine/src/hooks/useSchema.ts

把apiGroups作为参数传给fetchSchema，以免每次apiGroups变化，hooks都重新执行。

fix: fix useApiGroupSchema refresh bug

---

packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx

让editor支持显示更大的代码行数位数。本来是5，改成7。

fix: monaco editor show line number digits up to 7

---

packages/refine/src/App.tsx
packages/refine/src/Dovetail.tsx
packages/refine/src/constants/k8s.ts
packages/refine/src/contexts/constants.ts
packages/refine/src/hooks/useSchema.ts
packages/refine/src/models/workload-model.ts
packages/refine/src/utils/openapi.ts

1. 修改用来触发重新部署的的annotation的key，改成中性的key
2. 支持useSchema传入自定义的schema url前缀，而不是写死的。因为嵌套的过于深，所以创建了一个context用来传递。

fix oem bugs

---

packages/refine/package.json
packages/refine/src/App.tsx
packages/refine/src/components/EditField/index.tsx
packages/refine/src/components/Form/FormModal.tsx
packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/YamlForm.tsx
packages/refine/src/components/Form/useFieldsConfig.ts
packages/refine/src/components/Form/useYamlForm.ts
packages/refine/src/components/NamespacesFilter/index.tsx
packages/refine/src/components/ValueDisplay/index.tsx
packages/refine/src/hooks/useDeleteModal/useDeleteModal.tsx
packages/refine/src/hooks/useSchema.ts
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/pages/cronjobs/create/index.tsx
packages/refine/src/pages/daemonsets/create/index.tsx
packages/refine/src/pages/pods/create/index.tsx
packages/refine/src/styles/button.ts
packages/refine/src/styles/modal.ts
packages/refine/src/types/modal.d.ts
packages/refine/src/types/resource.ts
packages/refine/tools/linaria.ts
packages/refine/tsconfig.json
packages/refine/vite.config.ts
yarn.lock

支持表单模式转换为 YAML 编辑模式。
将表单当前值作为初始值赋给 YAML 编辑器，并在提交时进行 YAML 格式、Schema 和自定义逻辑校验。
会提示转换为表单后 YAML 编辑器所填内容会丢失，转换后会回到之前表单所填写的值。
主要代码在 useYamlForm。

feat: support chagne the ui form to yaml editor

---

packages/refine/src/components/DropdownMenuItems/EditAnnotationDropdownMenuItem.tsx
packages/refine/src/components/DropdownMenuItems/EditLabelDropdownMenuItem.tsx
packages/refine/src/components/DropdownMenuItems/EditNodeTaintDropdownMenuItem.tsx

修复一个已知问题，鼠标hover到dropdown item上面的时候，会出现 Uncaught TypeError: onItemHover is not a function。
经查，这个只会出现在自定义MenuItem组件中，原因是props传递的时候丢失了。所以自定义的MenuItem组件需要把props透传给 Menu.item 组件。
https://github.com/react-component/menu/issues/142#issuecomment-413041068

fix: fix onItemHover is not a function bug

---

packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx
packages/refine/src/pages/nodes/show/index.tsx

WorkloadPodsTable 添加 loading 的展示状态

feat: WorkloadPodsTable add loading

---

packages/refine/__tests__/plugins/validation.spec.ts
packages/refine/package.json
packages/refine/src/components/EditMetadataForm/EditAnnotationForm.tsx
packages/refine/src/components/EditMetadataForm/KeyValueTableForm.tsx
packages/refine/src/components/EditMetadataForm/LabelFormatPopover.tsx
packages/refine/src/utils/validation.ts

修改了注解和标签的校验规则，添加单测
1. 注解的Value不需要校验了。
2. 标签的name和prefix用一个正则校验

feat: fix annotation validation rule

---

packages/refine/src/App.tsx
packages/refine/src/components/CreateButton/index.tsx
packages/refine/src/components/Dropdowns/K8sDropdown/index.tsx
packages/refine/src/components/Form/FormModal.tsx
packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/YamlForm.tsx
packages/refine/src/components/Form/useRefineForm.ts
packages/refine/src/components/FormErrorAlert/index.tsx
packages/refine/src/components/Table/index.tsx
packages/refine/src/hooks/useDeleteModal/useDeleteModal.tsx
packages/refine/src/hooks/useFailedModal.tsx
packages/refine/src/locales/en-US/dovetail.json
packages/refine/src/locales/zh-CN/dovetail.json
packages/refine/src/styles/button.ts
packages/refine/src/styles/tag.ts
packages/refine/src/utils/string.ts
packages/refine/vite.config.ts

fix: improve the errors display

---

packages/refine/src/components/ConditionsTable/ConditionsTable.tsx

SKS-3394 show true/false status in condition table

---

packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/type.ts
packages/refine/src/components/Form/useYamlForm.ts

在校验函数传入当前的表单模式，以支持在不同模式下使用不同的校验

fix: update validators to include form mode parameter

---

packages/refine/__tests__/hooks/usePathMap.spec.ts
packages/refine/src/components/Form/FormModal.tsx
packages/refine/src/components/Form/useRefineForm.ts
packages/refine/src/hooks/usePathMap.ts
packages/refine/src/types/resource.ts
packages/refine/src/utils/object.ts

当前 refine form 使用 react-hook-form 来实现的，它不支持在字段路径中传入带有 `.` 的字段，需要手动在初始化和提交表单时对字段进行转换来绕过这个限制。
https://github.com/react-hook-form/react-hook-form/issues/3351
在表单中提供 `pathMap` 配置支持自动字段转换。
比如要配置 StorageClass 的 `parameters[csi.storage.k8s.io/fstype]` 字段，可以这样配置：
```
{
pathMap: [
[
['parameters', 'csi.storage.k8s.io/fstype'],
['parameters', 'fstype'],
]
],
fields() {
return [
{
path: ['parameters', 'fstype'],
key: 'fstype',
label: i18n.t('sks.fstype'),
...
},
]
}
}
```

feat: add usePathMap hook for form value transformations

---

packages/refine/src/App.tsx
packages/refine/src/components/Dropdowns/K8sDropdown/index.tsx
packages/refine/src/components/Form/FormModal.tsx
packages/refine/src/components/Form/FormModeSegmentControl.tsx
packages/refine/src/components/Form/RefineFormContainer.tsx
packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/YamlForm.tsx
packages/refine/src/components/Form/YamlFormContainer.tsx
packages/refine/src/components/Form/type.ts
packages/refine/src/components/Form/useFieldsConfig.ts
packages/refine/src/components/Form/useRefineForm.ts
packages/refine/src/components/Form/useYamlForm.ts
packages/refine/src/components/InternalBaseTable/index.tsx
packages/refine/src/components/ResourceCRUD/ResourceCRUD.tsx
packages/refine/src/components/ResourceCRUD/create/index.tsx
packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/hooks/useOpenForm.ts
packages/refine/src/pages/cronjobs/create/index.tsx
packages/refine/src/pages/daemonsets/create/index.tsx
packages/refine/src/pages/ingresses/index.tsx
packages/refine/src/pages/jobs/index.ts
packages/refine/src/pages/networkPolicies/index.tsx
packages/refine/src/pages/pods/create/index.tsx
packages/refine/src/pages/secrets/index.ts
packages/refine/src/pages/storageclasses/form/index.tsx
packages/refine/src/pages/storageclasses/index.ts
packages/refine/src/types/resource.ts

之前 formConfig 中把 RefineForm 和 YAMLForm 的配置字段混杂在一起，不容易分清哪些字段分别是针对哪种表单类型生效的。
现在在 formConfig 需明确声明表单类型，然后根据表单类型的不同填写不同的配置。
```ts
export type DefaultFormConfig<Model extends ResourceModel = ResourceModel> = {
formType: FormType.FORM;
/**
* 表单字段配置函数
* @param props 包含记录和动作类型的配置对象
* @returns 表单字段配置数组
*/
fields?: (props: {
record?: Model;
records: Model[];
action: 'create' | 'edit';
}) => RefineFormField[];
/** Refine Core 的表单属性 */
refineCoreProps?: UseFormProps['refineCoreProps'];
/** React Hook Form 的配置属性 */
useFormProps?: UseFormProps;
/** 是否禁用切换表单模式（在 YAML 和表单之间切换） */
isDisabledChangeMode?: boolean;
/** 表单标签的宽度
* 默认是 216px
*/
labelWidth?: string;
/**
* 自定义表单渲染函数
* @returns React节点
*/
renderForm?: () => React.ReactNode;
};
export type YamlFormConfig = {
formType: FormType.YAML;
};
export type …
```

refactor: update form handling and configuration structure

---

packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/type.ts
packages/refine/src/pages/storageclasses/form/index.tsx
packages/refine/src/pages/storageclasses/index.ts

根据 https://github.com/webzard-io/dovetail-v2/issues/228 实现表单联动。
之前的参数是按顺序一个个传的，现在参数变多之后不好读取，统一改成在一个对象里传。
```ts
// 移除了 formValue，因为从 `getValues` 中读取的不是响应式的，如果组件内需要可以使用 useWatch 进行读取
export type RefineFormFieldRenderProps = {
field: ControllerRenderProps<FieldValues, string>;
fieldConfig: RefineFormField;
action: 'edit' | 'create';
control: Control;
trigger: UseFormTrigger<FieldValues>;
};
```
改为直接使用 `extra` 属性来渲染，不用另写渲染逻辑

feat: enhance the form linkage

---

packages/refine/package.json
packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx
packages/refine/src/components/YamlEditor/YamlEditorComponent.tsx
packages/refine/src/types/window.d.ts

传入 value 来改变编辑器的值。
由于 Monaco 的 setDiagnosticsOptions 是设置全局配置的，不同项目间多次调用 setDiagnosticsOptions 会有冲突问题。
现在把 schemaMap 移到 window 下供其他项目获取，设置完整的 schemas。

feat: enhance MonacoYamlEditor with schema management and value synchronization

---

packages/refine/src/components/ShowContent/ShowContent.tsx
packages/refine/src/components/ShowContent/fields.tsx

支持在详情页展示自定义的名字，而不是固定的metadata.name

feat: support custom displayName in show

---

packages/refine/src/components/Form/useReactHookForm.tsx

registeredFields 来自于 getValue。但是当编辑表单的时候，要给表单填入资源的值的时候，getValue从表单获取到的还是空白的默认值，虽然也是经过transformInitValues的。但是如果transformInitValues中有一些需要条件判断的、默认值中不会添加的值，那么getValue的时候就获取不到，所以就不会被算在registeredFields中。所以不会不会被填入表单中。
解决办法是，根据transformedData来生成registeredFields，是最准确的。

fix: edit form cannot autofill custom fields

---

packages/refine/src/components/Form/RefineFormContent.tsx
packages/refine/src/components/Form/type.ts

在表单字段的渲染函数里面添加formValue参数，让单个字段可以访问表单中的其它字段的值

feat: add formValue in form field render function
