webzard-io/dovetail-v2

packages/refine/src/App.tsx, packages/refine/src/pages/deployments/index.ts, packages/refine/src/pages/deployments/show/index.tsx
=> use page to show deployment's detail

packages/refine/src/hooks/useDownloadYAML.ts, packages/refine/src/hooks/useEagleTable/index.tsx, packages/refine/src/utils/download.ts
=> feat: support download yaml

packages/refine/src/components/ConditionsTable/ConditionsTable.tsx, packages/refine/src/components/ConditionsTable/index.tsx, packages/refine/src/components/Show/Fields.tsx, packages/refine/src/components/Show/PageShow.tsx, packages/refine/src/components/Show/ShowContent.tsx, packages/refine/src/components/Show/Tags.tsx, packages/refine/src/hooks/useEagleTable/Columns.tsx, packages/refine/src/pages/deployments/show/index.tsx
1. 优化 deployment detail 页面
2. 添加 conditions table
=> refactor deployment detail page

packages/refine/src/App.tsx, packages/refine/src/components/K8sDropdown/index.tsx, packages/refine/src/components/Show/ShowContent.tsx, packages/refine/src/components/Show/Tags.tsx, packages/refine/src/hooks/useEagleTable/index.tsx, packages/refine/src/hooks/useEdit.ts, packages/refine/src/pages/configmap/index.ts
=> feat: add the action dropdown

packages/refine/src/components/Show/ShowContent.tsx, packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx
=> feat: support yaml view for detail

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/Breadcrumb/index.tsx, packages/refine/src/components/Layout/index.tsx, packages/refine/src/components/Table/TableToolBar.tsx, packages/refine/src/components/Table/index.tsx, packages/refine/src/pages/deployments/create/index.tsx, packages/refine/src/pages/deployments/list/index.tsx, packages/refine/src/styles.css, yarn.lock
- 修改样式
- 修复表单保存后无法自动跳转回列表页的问题
- 修复列表没有显示所有数据的问题
=> fix: change some ui styles and fix some bugs

packages/refine/src/App.tsx, packages/refine/src/components/Layout/index.tsx, packages/refine/src/components/Show/ShowContent.tsx, packages/refine/src/components/Table/TableToolBar.tsx, packages/refine/src/model/pod-model.ts, packages/refine/src/model/resource-model.ts, packages/refine/src/pages/configmap/show/index.tsx, packages/refine/src/pages/deployments/show/PodsList.tsx, packages/refine/src/pages/deployments/show/index.tsx, packages/refine/src/styles/global.css, packages/refine/src/types/resource.ts, packages/refine/src/utils/string.ts
1. 添加简单的 pod model
2. 添加 pod list
=> add pod list in deployment

packages/refine/src/App.tsx, packages/refine/src/components/FormLayout/index.tsx, packages/refine/src/components/Layout/index.tsx, packages/refine/src/components/Menu/index.tsx, packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx, packages/refine/src/components/YamlForm/index.tsx, packages/refine/src/pages/configmap/create/index.tsx, packages/refine/src/pages/deployments/create/index.tsx, packages/refine/src/styles/global.css
- 修改布局
- 添加选项控制编辑器滚动规则
- 封装表单组件
=> styles: change the page styles

packages/refine/package.json, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/model/resource-model.ts, packages/refine/src/pages/deployments/show/index.tsx, yarn.lock
k8s-api-provider 中增加了 metadata.relations 字段，基于它可以过滤 pods
=> filter pod with relation selector

packages/refine/src/components/FormLayout/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx
=> tweak style: make all title align

packages/refine/src/components/YamlForm/index.tsx, packages/refine/src/hooks/useEagleForm.ts, packages/refine/src/utils/error.ts, packages/refine/src/utils/schema.ts
=> feat: display the form errors

packages/refine/src/App.tsx, packages/refine/src/components/CronjobJobsTable/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/StateTag/StateTag.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/model/pod-model.ts, packages/refine/src/model/workload-model.ts, packages/refine/src/pages/pods/create/index.tsx, packages/refine/src/pages/pods/index.ts, packages/refine/src/pages/pods/list/index.tsx, packages/refine/src/pages/pods/show/index.tsx
1. 添加 pod crud
2. 支持在详情的pod列表中跳转到pod的详情
=> add Pods CRUD

packages/refine/src/components/CronjobJobsTable/index.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/model/job-model.ts, packages/refine/src/pages/jobs/list/index.tsx, packages/refine/src/pages/jobs/show/index.tsx, packages/refine/src/utils/time.ts
=> refine job list

packages/refine/src/App.tsx, packages/refine/src/components/ListPage/index.tsx, packages/refine/src/components/Table/index.tsx, packages/refine/src/pages/configmap/list/index.tsx, packages/refine/src/pages/cronjobs/list/index.tsx, packages/refine/src/pages/daemonsets/list/index.tsx, packages/refine/src/pages/deployments/list/index.tsx, packages/refine/src/pages/jobs/list/index.tsx, packages/refine/src/pages/pods/list/index.tsx, packages/refine/src/pages/statefulsets/list/index.tsx
=> fix: change styles and remove the configmap entry

packages/refine/package.json, packages/refine/src/components/ConditionsTable/ConditionsTable.tsx, packages/refine/src/components/PodContainersTable/PodContainersTable.tsx, packages/refine/src/components/PodContainersTable/index.ts, packages/refine/src/components/StateTag/StateTag.tsx, packages/refine/src/components/YamlEditor/yaml.worker.ts, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/model/job-model.ts, packages/refine/src/model/pod-model.ts, packages/refine/src/model/workload-model.ts, packages/refine/src/pages/pods/show/index.tsx, packages/refine/src/utils/addId.ts, yarn.lock
=> add container list in pod detail page

packages/refine/src/components/WorkloadReplicas/index.tsx, packages/refine/src/model/workload-model.ts, packages/refine/src/pages/daemonsets/show/index.tsx
https://github.com/webzard-io/dovetail-v2/assets/13651389/214e2c02-6555-4c3c-a5a1-d49e5bcd8b30
=> impl Deployment/Statefulset scale

packages/refine/.gitignore, packages/refine/package.json, packages/refine/playwright.config.ts, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx, packages/refine/src/hooks/useDeleteModal/useDeleteModal.tsx, packages/refine/src/model/job-model.ts, packages/refine/src/model/pod-model.ts, packages/refine/src/model/resource-model.ts, packages/refine/src/model/workload-model.ts, packages/refine/tests/crud.spec.ts, yarn.lock
https://github.com/webzard-io/dovetail-v2/assets/12260952/4e178622-4b2e-4f5d-970f-b631cb295fae
=> add Playwright tests

packages/refine/src/components/ResourceUsageBar/index.tsx, packages/refine/src/components/WorkloadReplicas/index.tsx, packages/refine/src/model/pod-metrics-model.ts, packages/refine/src/model/pod-model.ts, packages/refine/src/pages/pods/list/index.tsx, packages/refine/src/types/metric.ts, packages/refine/src/utils/unit.ts
1. only show metric columns when the metric server installed
2. display metric columns in si format
3. implement the `<ResourceUsageBar />`, as an option to display metrics
=> integrate pod metrics from metric server

packages/refine/src/components/ResourceCRUD/ResourceCRUD.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/pages/configmaps/index.ts, packages/refine/src/pages/secrets/index.ts
=> improve ConfigMap and Secret views

packages/refine/package.json, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx, packages/refine/src/components/YamlEditor/YamlEditorComponent.tsx, packages/refine/src/hooks/useEagleForm.ts, packages/refine/src/hooks/useK8sYamlEditor.ts, packages/refine/src/utils/k8s.ts, packages/refine/vite.config.ts, yarn.lock
=> feat: auto fold unimportant props in yaml editor

packages/refine/src/components/CronJobDropdown/index.tsx, packages/refine/src/components/CronjobJobsTable/index.tsx, packages/refine/src/components/EventsTable/EventsTable.tsx, packages/refine/src/components/K8sDropdown/index.tsx, packages/refine/src/components/ListPage/index.tsx, packages/refine/src/components/PageShow/PageShow.tsx, packages/refine/src/components/ResourceCRUD/list/index.tsx, packages/refine/src/components/ResourceCRUD/show/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/Table/index.tsx, packages/refine/src/components/WorkloadDropdown/index.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/contexts/component.ts, packages/refine/src/contexts/index.ts, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx, packages/refine/src/index.ts, packages/refine/src/types/resource.ts
添加 ComponentContext 支持外部使用自定义的 UI 组件来进行渲染，并调整 Table 的 props 接口定义。
=> feat: add the component context

packages/refine/src/Dovetail.tsx, packages/refine/src/main.tsx
=> fix: don't import ui-kit styles in prod mode

packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/plugins/relation-plugin.ts
调整 relation plugin 设置的字段顺序
YAML 模式下关闭  liveMode
=> fix some issues of the show page

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/FormModal/index.tsx, packages/refine/src/components/ResourceCRUD/ResourceCRUD.tsx, packages/refine/src/components/WorkloadDropdown/index.tsx, packages/refine/src/components/YamlForm/index.tsx, packages/refine/src/hooks/useEagleForm.ts, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx, packages/refine/src/hooks/useOpenForm.ts, packages/refine/src/pages/deployments/show/index.tsx, packages/refine/vite.config.ts, yarn.lock
之前通过 ref 的方式拿到子组件的 `saveButtonProps` 没法响应式，现在改成 state + event 的方式拿值。
另外修改配置修复启动开发模式时报错和 loading 图标展示不正确的问题。
=> fix: make saveButtonProps reactive and use modal mode as default

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/ReferenceLink/index.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/components/index.ts, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/job-model.ts, packages/refine/src/models/service-model.ts, packages/refine/src/models/workload-model.ts, packages/refine/src/pages/daemonsets/list/index.tsx, packages/refine/src/pages/jobs/index.ts, packages/refine/src/pages/pods/list/index.tsx, packages/refine/src/utils/time.ts, yarn.lock
对齐了各个资源的列表组件
1. 添加了 deamonset 的 restarts
2. 修复了 WorkloadPodsTable 只能获取 10 的 pod的bug（禁用分页）、
3. 给 job的持续时间添加了 i18n
4. 给 job model 添加了 pod，用来计算 restarts
5. 添加了service model，但因为需求文档还不清楚，未全部完成
6. 给 pod 添加了一个 workload 跳转链接，可以跳转到对应的workload资源
=> Check resources fields

packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/StateTag/StateTag.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx
=> fix: fix some style issues

packages/refine/package.json, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/WorkloadReplicas/index.tsx, packages/refine/src/locales/zh-CN/dovetail.json, yarn.lock
=> feat: change the replicas component

packages/refine/src/components/Time/index.tsx, packages/refine/src/i18n.ts
=> Creation time show time period

packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/types/resource.ts
=> feat: add the new resource groups

packages/refine/src/constants/k8s.ts, packages/refine/src/pages/secrets/index.ts, packages/refine/src/pages/services/index.tsx
=> feat: change the default values

packages/refine/src/components/CronJobDropdown/index.tsx, packages/refine/src/components/CronjobJobsTable/index.tsx, packages/refine/src/components/FormErrorAlert/index.tsx, packages/refine/src/components/FormModal/index.tsx, packages/refine/src/components/ImageNames/index.tsx, packages/refine/src/components/K8sDropdown/index.tsx, packages/refine/src/components/KeyValueData/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/ShowContent/groups.tsx, packages/refine/src/components/ShowContent/tabs.tsx, packages/refine/src/components/StateTag/StateTag.tsx, packages/refine/src/components/Table/index.tsx, packages/refine/src/components/Time/index.tsx, packages/refine/src/components/WorkloadDropdown/index.tsx, packages/refine/src/components/YamlForm/index.tsx, packages/refine/src/hooks/useDeleteModal/useDeleteModal.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/cronjob-model.ts, packages/refine/src/pages/cronjobs/show/index.tsx
=> feat: change the cronjob page

packages/refine/src/components/IngressRulesComponent/index.tsx, packages/refine/src/models/ingress-model.ts
改进ingress rule的显示
只有当rule中有host，且path中没有*时，才显示成可以点的链接
=> improve ingress rules display

packages/refine/src/components/ListPage/index.tsx, packages/refine/src/components/Table/TableToolBar.tsx, packages/refine/src/pages/configmaps/index.ts, packages/refine/src/types/resource.ts
=> feat: add the resource description

packages/refine/src/components/ImageNames/index.tsx, packages/refine/src/components/KeyValue/KeyValueAnnotation.tsx, packages/refine/src/components/ServiceComponents/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/ValueDisplay/index.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx
新增 ValueDisplay 组件来处理资源没有值时展示为 `-`，以及显示 title。
=> feat: add the ValueDisplay component

packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/Form/YamlForm.tsx, packages/refine/src/components/Form/useYamlForm.ts, packages/refine/src/components/ResourceCRUD/create/index.tsx, packages/refine/src/constants/k8s.ts, packages/refine/src/pages/secrets/index.ts, packages/refine/src/types/resource.ts
支持在初始化和提交时转换表单的值。
比如 Secret Data 在提交时需转换为 base64。
=> feat: support transform values

packages/refine/src/Dovetail.tsx, packages/refine/src/components/CronJobDropdown/index.tsx, packages/refine/src/components/EditField/index.tsx, packages/refine/src/components/K8sDropdown/index.tsx, packages/refine/src/components/ReplicasDropdown/index.tsx, packages/refine/src/components/ResourceCRUD/list/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/Table/TableToolBar.tsx, packages/refine/src/components/WorkloadDropdown/index.tsx, packages/refine/src/constants/auth.ts, packages/refine/src/constants/index.ts
=> feat: add the access control

packages/refine/src/components/ServiceComponents/index.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/service-model.ts
修改 Service 的「类型」、「集群内访问方式」、「集群外访问方式」、「端口映射」字段。
=> fix: change some fields of service

packages/refine/src/components/Form/RefineFormContent.tsx
=> editing name is not allowed

packages/refine/src/Dovetail.tsx, packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/ResourceCRUD/ResourceCRUD.tsx, packages/refine/src/types/resource.ts
1. 给表单添加 formTitle 和 formDesc 的配置项
2. Dovetail 组件支持传入 customRouterProvider 参数
=> update Dovetail config

packages/refine/src/components/ConditionsTable/ConditionsTable.tsx, packages/refine/src/components/CronjobJobsTable/index.tsx, packages/refine/src/components/EditField/index.tsx, packages/refine/src/components/EventsTable/EventsTable.tsx, packages/refine/src/components/IngressRulesTable/IngressRulesTable.tsx, packages/refine/src/components/KeyValue/KeyValue.tsx, packages/refine/src/components/NetworkPolicyRulesViewer/NetworkPolicyRulesViewer.tsx, packages/refine/src/components/PodContainersTable/PodContainersTable.tsx, packages/refine/src/components/PodLog/index.tsx, packages/refine/src/components/PodSelectorTable/index.tsx, packages/refine/src/components/PortsTable/index.tsx, packages/refine/src/components/Table/index.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/hooks/useDeleteModal/useDeleteModal.tsx, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx
1. change the styles
2. fix the pagination
=> fix: fix some issues

packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/Form/RefineFormContent.tsx, packages/refine/src/components/Form/RefineFormPage.tsx, packages/refine/src/components/Form/type.ts, packages/refine/src/components/Form/useRefineForm.ts
=> RefineForm support render custom field

packages/refine/src/components/Form/useYamlForm.ts, packages/refine/src/components/KeyValue/KeyValue.tsx, packages/refine/src/components/NamespacesFilter/index.tsx, packages/refine/src/components/StateTag/StateTag.tsx, packages/refine/src/components/Tags/index.tsx
1. 修改状态标签的展示
2. 仅支持一次输入一个 YAML 配置（文案在稍后的 MR 中提供）
3. 修改标签样式
4. 修改名字空间过滤器。现支持展示 8 个后才进行省略，宽度随展示的数量变化
=> feat: improve the components

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/Form/RefineFormContent.tsx, packages/refine/src/components/Form/RefineFormPage.tsx, packages/refine/src/components/Form/type.ts, packages/refine/src/components/Form/useRefineForm.ts, packages/refine/src/components/ResourceCRUD/list/index.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx, packages/refine/src/types/resource.ts
1. 修复 RefineForm 第一次请求出错的时候，不显示错误信息的bug。
2. 支持传递record，records等上下文给refineForm的fileds配置，以实现动态的表单配置功能
3. 给refineFormField添加 helperText和placeholder参数
4. 支持在resourceConfig中配置tableProps
=> some improvements and bugfix

packages/refine/src/components/EventsTable/EventsTable.tsx
=> EventsTable 50 per page

packages/refine/src/components/ConditionsTable/ConditionsTable.tsx, packages/refine/src/components/Time/index.tsx
=> fix(Condition): use the lastTransitionTime for the updated time

packages/refine/src/components/KeyValue/KeyValueSecret.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx
=> fix: dont show the eye button when there are no data

packages/refine/src/components/ServiceComponents/index.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/en-US/dovetail.json, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/service-model.ts
=> SKS-2630 fix service columns display

packages/refine/package.json, packages/refine/src/components/EditField/index.tsx, packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/ReplicasDropdown/index.tsx, packages/refine/src/hooks/useOpenForm.ts, packages/refine/src/types/modal.d.ts, yarn.lock
0.29.x 版本中
- 处理相关 breaking change pushModal 被弃用，替换为 usePushModal
@tanbowensg @MrWindlike PTAL
=> TOWER-12338 update eagle to next version

packages/refine/src/components/IngressRulesComponent/index.tsx, packages/refine/src/components/ResourceLink/index.tsx
=> SKS-2589 remove link padding

packages/refine/src/components/ErrorContent/index.tsx, packages/refine/src/components/KeyValue/KeyValueSecret.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/constants/k8s.ts, packages/refine/src/locales/en-US/dovetail.json
1. 修改详情页卡片的样式
2. 修改文案
3. 修改 secret 默认值
=> Fix/d2: styles, secret, texts

packages/refine/src/Dovetail.tsx, packages/refine/src/components/IngressRulesComponent/index.tsx, packages/refine/src/components/IngressRulesTable/IngressRulesTable.tsx, packages/refine/src/components/LinkFallback/index.tsx, packages/refine/src/components/PodLog/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/utils/error.ts
1. 让 Ingress 规则变为可跳转
2. Pod 日志 - 点击「自动换行」时将滚动条移到最下面
https://github.com/webzard-io/dovetail-v2/assets/25414733/309159ff-d194-4449-aa4c-bbfb62b96228
3. 修改错误信息格式
4. 修改部分列为不可排序
=> Fix/d2: columns, pod log, error message

packages/refine/src/components/ListPage/index.tsx, packages/refine/src/models/cronjob-model.ts, packages/refine/src/models/daemonset-model.ts, packages/refine/src/models/deployment-model.ts, packages/refine/src/models/event-model.ts, packages/refine/src/models/ingress-model.ts, packages/refine/src/models/job-model.ts, packages/refine/src/models/network-policy-model.ts, packages/refine/src/models/node-model.ts, packages/refine/src/models/persistent-volume-claim.ts, packages/refine/src/models/persistent-volume.ts, packages/refine/src/models/pod-metrics-model.ts, packages/refine/src/models/pod-model.ts, packages/refine/src/models/resource-model.ts, packages/refine/src/models/service-model.ts, packages/refine/src/models/statefulset-model.ts, packages/refine/src/models/storage-class.ts, packages/refine/src/models/workload-base-model.ts, packages/refine/src/models/workload-model.ts
- 给 ListPage 添加 contentClassName
- 让 model 中的 globalStore 属性变为不可枚举的，因为在一些库中如果读取到 globalStore 可能会出现一些错误。
=> feat: add some props and change the globalStore

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/ResourceFiledDisplays.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/ShowContent/groups.tsx, packages/refine/src/components/index.ts, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/en-US/dovetail.json, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/pages/persistentvolumeclaims/index.ts, packages/refine/src/pages/storageclasses/index.ts
=> feat: add more pvc columns and fields

packages/refine/src/components/Form/YamlForm.tsx, packages/refine/src/components/Form/useYamlForm.ts, packages/refine/src/components/NetworkPolicyRulesViewer/NetworkPolicyRulesViewer.tsx, packages/refine/src/components/YamlEditor/MonacoYamlEditor.tsx, packages/refine/src/components/YamlEditor/YamlEditorComponent.tsx, packages/refine/src/hooks/useSchema.ts, packages/refine/src/utils/openapi.ts, packages/refine/src/utils/schema.ts
1. 为了让YamlEditor支持多个schema，所以要把YamlEditor的schema参数改成接受一个schema数组。
=> feat: yaml editor support multiple schema

packages/refine/src/index.ts, packages/refine/src/utils/index.ts, packages/refine/src/utils/schema.ts
=> feat: improve and export some schema methods

packages/refine/package.json, packages/refine/src/components/FormErrorAlert/index.tsx
=> feat: FormErrorAlert support custom title

packages/refine/src/App.tsx, packages/refine/src/Dovetail.tsx, packages/refine/src/components/DropdownMenuItems/EditAnnotationDropdownMenuItem.tsx, packages/refine/src/components/DropdownMenuItems/EditLabelDropdownMenuItem.tsx, packages/refine/src/components/DropdownMenuItems/index.ts, packages/refine/src/components/EditField/index.tsx, packages/refine/src/components/EditMetadataForm/EditAnnotationForm.tsx, packages/refine/src/components/EditMetadataForm/EditLabelForm.tsx, packages/refine/src/components/EditMetadataForm/index.ts, packages/refine/src/components/K8sDropdown/index.tsx, packages/refine/src/components/index.ts, packages/refine/src/locales/en-US/dovetail.json, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/resource-model.ts
1. 添加编辑标签和注解的弹窗
2. 为了支持样式隔离，支持给Dovetail传入antdGetPopupContainer参数来指定message弹出的容器
3. 添加了编辑标签和注解的MenuItem，以便添加到自定义的Dropdown中
=> feat: add Edit Label&Annotation Form

packages/refine/jest.config.js, packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/Form/YamlForm.tsx, packages/refine/src/components/Form/useReactHookForm.tsx, packages/refine/src/components/Form/useRefineForm.ts, packages/refine/src/components/Form/useYamlForm.ts, packages/refine/src/components/PVCDistributeStorage/index.tsx, packages/refine/src/components/ResourceCRUD/list/index.tsx, packages/refine/src/components/ResourceTable/index.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/ShowContent/groups.tsx, packages/refine/src/components/index.ts, packages/refine/src/constants/k8s.ts, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/hooks/useEagleTable/useEagleTable.tsx, packages/refine/src/locales/en-US/dovetail.json, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/persistent-volume-claim.ts, packages/refine/src/models/persistent-volume.ts, packages/refine/src/models/storage-class.ts, packages/refine/src/pages/secrets/index.ts, packages/refine/src/types/resource.ts, packages/refine/src/utils/storage.ts
1. 新增 PV, PVC, SC 相关字段
2. 表单支持使用 transformApplyValues 来在提交前进行转换值
3. 新增 ResourceTable 组件，方便在详情页中展示相关资源的表格
4. 支持编辑 PVC 存储
=> feat: improve resources(PV, PVC, SC)

packages/refine/package.json, packages/refine/src/components/ConditionsTable/ConditionsTable.tsx, packages/refine/src/components/Dropdowns/K8sDropdown/index.tsx, packages/refine/src/components/ErrorContent/index.tsx, packages/refine/src/components/IngressRulesTable/IngressRulesTable.tsx, packages/refine/src/components/NetworkPolicyRulesViewer/NetworkPolicyRulesViewer.tsx, packages/refine/src/components/NodeTaintsTable/NodeTaintsTable.tsx, packages/refine/src/components/PVCDistributeStorage/index.tsx, packages/refine/src/components/PodContainersTable/PodContainersTable.tsx, packages/refine/src/components/PodSelectorTable/index.tsx, packages/refine/src/components/PortsTable/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/components/WorkloadPodsTable/WorkloadPodsTable.tsx, packages/refine/src/components/index.ts, packages/refine/src/constants/k8s.ts, packages/refine/src/models/event-model.ts, yarn.lock
1. change some styles
2. remove edit label and annotation from K8sDropdown
3. fix the error of EventTable
=> fix: improve some details

packages/refine/src/components/EventsTable/EventsTable.tsx, packages/refine/src/hooks/useSchema.ts, packages/refine/src/utils/openapi.ts, packages/refine/src/utils/schema-store.ts
=> feat: improve the schemas fetching

packages/refine/package.json, packages/refine/src/components/DropdownMenuItems/index.ts, packages/refine/src/components/EditMetadataForm/EditNodeTaintForm.tsx, packages/refine/src/components/EditMetadataForm/KeyValueTableForm.tsx, packages/refine/src/locales/zh-CN/dovetail.json, yarn.lock
=> feat: improve node taint form select

packages/refine/package.json, packages/refine/src/components/Dropdowns/K8sDropdown/index.tsx, packages/refine/src/components/PVCDistributeStorage/index.tsx, packages/refine/src/components/PodContainersTable/PodContainersTable.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/constants/k8s.ts, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/pages/storageclasses/index.ts, packages/refine/src/types/resource.ts
1. 修复容器列表的排序
2. 支持隐藏编辑按钮
3. PVC 存储添加最大限制
=> feat: change some resources details

packages/refine/src/components/Form/FormModal.tsx, packages/refine/src/components/PVCDistributeStorage/index.tsx, packages/refine/src/components/ResourceLink/index.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/locales/en-US/dovetail.json, packages/refine/src/locales/zh-CN/dovetail.json, packages/refine/src/models/persistent-volume-claim.ts
=> fix: fix some issues of resources

packages/refine/package.json, packages/refine/src/App.tsx, packages/refine/src/components/Form/RefineFormContent.tsx, packages/refine/src/components/ResourceLink/index.tsx, packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/models/persistent-volume.ts, packages/refine/src/types/resource.ts
1. 修复部分样式问题
2. 表单支持自定义 label 宽度
=> fix: change some styles

packages/refine/package.json, packages/refine/src/components/CreateButton/index.tsx, packages/refine/src/types/resource.ts
=> feat: support custom create button text

packages/refine/package.json, packages/refine/src/components/Form/FormModal.tsx
=> fix: hide form alert when isDisabledChangeMode

packages/refine/package.json, packages/refine/src/components/ServiceComponents/index.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/pages/services/index.tsx
将端口跳转逻辑从「端口映射」改为「集群外访问方式」，跳转链接为「vip:port」
=> feat: change some fields of service

packages/refine/src/components/WorkloadReplicas/index.tsx
=> SKS-2519 fix replica chart radius

packages/refine/src/App.tsx, packages/refine/src/components/PageShow/PageShow.tsx, packages/refine/src/components/ResourceLink/index.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/hooks/useEagleTable/columns.tsx, packages/refine/src/models/persistent-volume.ts, packages/refine/vite.config.ts
在 PV 页面点击跳转到 PVC 详情页时，应该附带上 PVC uid，并用 PVC uid 判断是否为同一个资源，不是的话则提示资源不存在
=> feat: update PVC reference fields and columns with UID information

packages/refine/src/components/NodeTaintsTable/NodeTaintsTable.tsx
=> SKS-3229 node taint table use eagle table

packages/refine/package.json, packages/refine/src/components/NetworkPolicyRulesViewer/NetworkPolicyRulesViewer.tsx, packages/refine/src/components/YamlEditor/YamlEditorComponent.tsx, packages/refine/src/components/YamlEditor/style.ts, packages/refine/vite.config.ts
- 使用到 monaco 的组件都改为懒加载，并修改 external 为所有依赖的包。
- 修复编辑器样式
=> feat: add lazy load for monaco editor

packages/refine/package.json, packages/refine/src/components/PodShellModal/PodShell.tsx, packages/refine/src/components/PodShellModal/index.tsx, packages/refine/src/components/Shell/Connecting.tsx, packages/refine/src/components/Shell/common.ts, packages/refine/src/components/Shell/index.tsx, packages/refine/src/components/index.ts, packages/refine/src/shell.ts, packages/refine/tsconfig.json, packages/refine/vite.config.ts
把 Shell 组件移到单独的入口文件中，方便外部按需引入。
=> feat: splitting shell to the independent entry

packages/refine/src/components/ShowContent/ShowContent.tsx, packages/refine/src/components/ShowContent/fields.tsx, packages/refine/src/pages/deployments/show/index.tsx
在showConfig中添加basicGroup字段，可以在tab上面展示常驻信息
=> feat: add basicGroup

packages/refine/src/models/pod-model.ts
=> feat: add ips in PodModel
